# Generated by Django 4.1.3 on 2022-11-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Topic List',
            },
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topiclist')),
            ],
            options={
                'verbose_name_plural': 'Question List',
            },
        ),
    ]
