# Generated by Django 4.1.3 on 2022-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='answer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlist',
            name='photo',
            field=models.ImageField(default='', max_length=254, upload_to='picture/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
