# Generated by Django 4.1.3 on 2022-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questionlist_answer_questionlist_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
