# Generated by Django 4.1.3 on 2022-12-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlist',
            old_name='topic_name',
            new_name='topic_id',
        ),
    ]
